# Generated by Django 4.2.7 on 2025-11-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('quantity', models.IntegerField(verbose_name='Количество проданных единиц')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка')),
            ],
            options={
                'verbose_name': 'Продажа по месяцам',
                'verbose_name_plural': 'Продажи по месяцам',
                'db_table': 'monthly_sales',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month', 'product_name')},
            },
        ),
    ]
